#pragma once
/*
   -- SAKUARM --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#if defined(BLE)
  #define REMOTEXY_MODE__ESP32CORE_BLE
  #include <BLEDevice.h>
#elif defined(BTCL)
  #define REMOTEXY_MODE__ESP32CORE_BLUETOOTH
  #include <BluetoothSerial.h>
#endif

// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "SAKUARM"


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 283 bytes V19 
  { 255,4,0,26,0,20,1,19,0,0,0,0,31,2,106,200,200,90,1,1,
  11,0,71,237,11,67,67,27,4,31,31,58,0,2,24,255,0,0,52,67,
  0,0,52,195,0,0,240,65,0,0,32,65,0,0,0,0,24,0,73,80,
  49,7,71,129,7,64,4,5,128,0,2,26,0,0,200,194,0,0,200,66,
  0,0,0,0,73,95,11,7,71,193,11,4,65,4,128,0,2,26,0,0,
  200,194,0,0,200,66,0,0,0,0,70,73,13,40,40,161,69,13,13,16,
  26,134,0,1,11,7,53,53,131,27,18,18,0,2,31,0,1,22,27,40,
  40,131,50,18,18,0,2,31,0,71,239,98,69,69,3,30,31,31,58,0,
  2,24,255,0,0,52,67,0,0,52,195,0,0,240,65,0,0,32,65,0,
  0,0,0,24,0,71,237,138,69,69,27,57,31,31,58,0,2,24,255,0,
  0,52,67,0,0,52,195,0,0,240,65,0,0,32,65,0,0,0,0,24,
  0,71,49,22,69,69,153,29,31,31,58,0,2,24,255,0,0,52,67,0,
  0,52,195,0,0,240,65,0,0,32,65,0,0,0,0,24,0,70,15,22,
  29,29,41,39,13,13,16,26,1,0,5,239,16,133,133,61,14,69,69,32,
  2,26,31 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  uint8_t button_05; // =1 if button pressed, else =0, from 0 to 1
  uint8_t button_06; // =1 if button pressed, else =0, from 0 to 1
  int8_t joystick_01_x; // from -100 to 100
  int8_t joystick_01_y; // from -100 to 100

    // output variables
  float instrument_01; // from 180 to -180
  float linearbar_01; // from -100 to 100
  float linearbar_02; // from -100 to 100
  uint8_t led_01; // from 0 to 1
  float instrument_02; // from 180 to -180
  float instrument_03; // from 180 to -180
  float instrument_04; // from 180 to -180
  uint8_t led_02; // from 0 to 1

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

