#pragma once

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#if defined(BLE)
  #define REMOTEXY_MODE__ESP32CORE_BLE
  #include <BLEDevice.h>

#elif defined(BTCL)
  #define REMOTEXY_MODE__ESP32CORE_BLUETOOTH
  #include <BluetoothSerial.h>

#endif

// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "HARUROBO_assembled"


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 350 bytes V19 
  { 255,12,0,14,0,87,1,19,0,0,0,0,31,2,106,200,200,92,1,1,
  18,0,5,217,26,130,130,26,14,60,60,32,2,26,31,70,241,170,39,39,
  5,71,15,15,16,26,134,0,10,25,139,52,52,100,70,16,16,48,4,26,
  31,79,78,0,31,79,70,70,0,71,34,81,65,65,117,4,20,20,56,0,
  2,24,135,0,0,52,67,0,0,0,0,0,0,240,65,0,0,32,65,0,
  0,32,65,24,0,71,19,67,63,63,139,4,20,20,56,0,2,24,135,0,
  0,52,67,0,0,0,0,0,0,240,65,0,0,32,65,0,0,32,65,24,
  0,71,26,122,63,63,161,4,20,20,56,0,2,24,135,0,0,52,67,0,
  0,0,0,0,0,240,65,0,0,32,65,0,0,32,65,24,0,1,74,0,
  52,52,173,43,15,15,0,2,31,226,135,167,0,1,83,56,33,33,173,61,
  15,15,0,2,31,226,135,169,0,1,80,143,33,33,118,26,15,15,0,2,
  31,226,134,144,0,1,72,6,33,33,161,26,15,15,0,2,31,226,134,183,
  0,5,12,37,130,130,117,30,60,60,32,2,26,31,129,66,50,8,13,125,
  18,4,6,64,24,49,0,129,78,54,8,13,147,18,4,6,64,24,50,0,
  129,97,57,8,13,169,18,4,6,64,24,51,0,1,51,61,33,33,21,7,
  18,18,0,2,31,226,134,182,0,1,74,61,33,33,73,7,18,18,0,2,
  31,226,134,183,0,70,78,37,39,39,182,16,12,12,16,26,37,0,4,50,
  35,7,78,20,76,71,11,176,2,26 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  int8_t joystick_01_x; // from -100 to 100
  int8_t joystick_01_y; // from -100 to 100
  uint8_t pushSwitch_01; // =1 if state is ON, else =0, from 0 to 1
  uint8_t button_01; // =1 if button pressed, else =0, from 0 to 1
  uint8_t button_02; // =1 if button pressed, else =0, from 0 to 1
  uint8_t button_03; // =1 if button pressed, else =0, from 0 to 1
  uint8_t button_04; // =1 if button pressed, else =0, from 0 to 1
  int8_t joystick_02_x; // from -100 to 100
  int8_t joystick_02_y; // from -100 to 100
  uint8_t button_05; // =1 if button pressed, else =0, from 0 to 1
  uint8_t button_06; // =1 if button pressed, else =0, from 0 to 1
  int8_t slider_01; // from -100 to 100

    // output variables
  uint8_t led_01; // from 0 to 1
  float instrument_01; // from 180 to 0
  float instrument_02; // from 180 to 0
  float instrument_03; // from 180 to 0
  uint8_t led_02; // from 0 to 1

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////

/*
   -- harurobo --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

